all: build

build:
	g++ main.cpp tablica.cpp menu.cpp tablica_wysw.cpp pliki.cpp tablica_funkcje.cpp -o program.out
	
debug:
	g++ -g main.cpp tablica.cpp menu.cpp tablica_wysw.cpp pliki.cpp tablica_funkcje.cpp -o program.out
